query getEncounterById($id: Int!) {
  encounters_by_pk(id: $id) {
    id
    active
    energy_cost
    power
    max_rats
    encounter_weaknesses {
      weakness
    }
    encounter_resistances {
      resistance
    }
    reward {
      tokens
    }
    encounter_rat_constraints {
      rat_type
      locked_slots
      external_contract_address
    }
  }
}
